### ISSUE TITLE
Debian release

### ISSUE THREAD

**Issue by Timple** [yoshito-n-students/remote_rosbag_record#6]
Would you be interested in creating a debian release?

It is actually not that hard if you follow this official tutorial:
http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

I've done it a couple of times and I am willing to assist if the effort is too big or the priority too low on your side :sunglasses:

**Comment by yoshito-okada** [comment]
@Timple I think I can do it by myself because I have released other packages.  Are you happy if I release it for kinetic & melodic?

**Comment by Timple** [comment]
Only Melodic for us. Kinetic is up to you :)

**Comment by yoshito-okada** [comment]
@Timple 
I just made a PR to release this package for melodic (and also kinetic).
https://github.com/ros/rosdistro/pull/24177

If possible, try the package on the testing repository and let me know if you find something.

**Comment by Timple** [comment]
Awesome! I'll evaluate

**Comment by Timple** [comment]
Works like a charm, sorry I didn't respond earlier.

Would you mind releasing for Noetic as well? Since the release is around the corner and the [call for testing](https://discourse.ros.org/t/ros-noetic-call-for-testing) came today.

**Comment by yoshito-okada** [comment]
Done!
https://github.com/ros/rosdistro/pull/25111
