### ISSUE TITLE
The "name" Parameter does not work

### ISSUE THREAD

**Issue by FHof** [yoshito-n-students/remote_rosbag_record#7]
### Problem description

The `name` Parameter, which should define the output path for the bag file, is ignored when I run the remote_rosbag_record record. The other Parameters, e.g. `prefix`, are recognized.

### How to reproduce

```sh
# Start ROS
roscore

# Run the remote rosbag recorder
rosrun remote_rosbag_record record _record_all:=true _name:="/tmp/test.bag"

# Start the recording
rosrun remote_rosbag_record trigger _regex:=/start

# View the remote_rosbag_record output.
# It shows something like "Recording to '2020-09-25-12-56-11.bag'"
```

### Additional information

Version: `0.0.2-1bionic.20200821.014813` (the `ros-melodic-remote-rosbag-record` apt package)

I cannot execute/find the joy_listener with rosrun (`rosrun remote_rosbag_record joy_listener`), so I hope the version shown in the apt package is correct.

**Comment by yoshito-okada** [comment]
Thank you for posting the issue. This is simply because `rosbag::Recorder` which is a backend of `remote_rosbag_record` ignores the `name` option.  Please use `prefix` with `append_date:=false` instead.  I will update the wiki.

**Comment by FHof** [comment]
Thanks for the quick response. I can confirm that `prefix` without `append_date` work well enough to set the output file path.
