### ISSUE TITLE
Exception after triggering a stop: "Attempt to unload library that class_loader is unaware of."

### ISSUE THREAD

**Issue by FHof** [yoshito-n-students/remote_rosbag_record#8]
### Problem description

When I stop the remote rosbag recorder, it shows an error message. The bag file appears but I don't think that the recorder is supposed to crash.
Here are the output messages:
```
root@c5b4233484b3:~# rosrun remote_rosbag_record record _record_all:=true
[ INFO] [1601039099.065574728]: Start recording
[ INFO] [1601039099.080521473]: Recording to '2020-09-25-13-04-59.bag'.
[ INFO] [1601039099.081094350]: Subscribing to /is_recording
[ INFO] [1601039099.083109417]: Subscribing to /rosout
[ INFO] [1601039099.084519307]: Subscribing to /rosout_agg
[ INFO] [1601039102.739659818]: Stop recording
terminate called after throwing an instance of 'class_loader::LibraryUnloadException'
  what():  Attempt to unload library that class_loader is unaware of.
Aborted (core dumped)
```

### How to reproduce

```sh
# Start ROS
roscore

# Run the remote rosbag recorder
rosrun remote_rosbag_record record _record_all:=true

# Start and stop the recording
rosrun remote_rosbag_record trigger _regex:=/start
rosrun remote_rosbag_record trigger _regex:=/stop

# View the error message in the remote_rosbag_record output.
```

### Additional information

Version: `0.0.2-1bionic.20200821.014813` (the `ros-melodic-remote-rosbag-record` apt package)

**Comment by yoshito-okada** [comment]
Thank you for reporting the issue.  I reproduced the problem.

I think this is not a problem of this package but of class_loader (see comments below for details).
https://github.com/jonbinney/moveit/blob/57bd476bf7de5a41ba1e0deb856d1ae79614ef64/moveit_ros/planning/robot_model_loader/src/robot_model_loader.cpp#L56

However, as a workaround, I just made a commit 2d2f390e3a184e4fd8ace786fbb6643d5ae2a93f to avoid the exception from class_loader and released as 0.0.3.  Try the latest master branch or wait for the next update of apt.

**Comment by yoshito-okada** [comment]
This would be better explanation about this issue.
https://github.com/ros-planning/moveit_ros/blob/ea3a80b6cece2cf9cd6f37734dafb9b3056b41a8/planning_interface/common_planning_interface_objects/src/common_objects.cpp#L64

Anyway what I can only do in my package is to manually destroy the rosbag recorder.  So I will keep the present code until class_loader is fixed.

**Comment by FHof** [comment]
A bag file appears either way, so I'm going to wait for the next update of apt. Thanks for the fix/workaround.
